//
// ContactsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class ContactsAPI: APIBase {
    /**
     Delete Contacts
     
     - parameter listId: (form) The list of contacts to be deleted. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func deleteContacts(listId listId: String, completion: ((error: ErrorType?) -> Void)) {
        deleteContactsWithRequestBuilder(listId: listId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Delete Contacts
     - PUT /contacts/delete
     - Delete contacts
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     
     - parameter listId: (form) The list of contacts to be deleted. 

     - returns: RequestBuilder<Void> 
     */
    public class func deleteContactsWithRequestBuilder(listId listId: String) -> RequestBuilder<Void> {
        let path = "/contacts/delete"
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "listId": listId
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
