//
// FormsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class FormsAPI: APIBase {
    /**
     Get csv
     
     - parameter id: (path) Id of the form 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getFormTrackingAsCsv(id id: String, completion: ((error: ErrorType?) -> Void)) {
        getFormTrackingAsCsvWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Get csv
     - GET /forms/{id}/tracking/export
     - Get form tracking as csv
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     
     - parameter id: (path) Id of the form 

     - returns: RequestBuilder<Void> 
     */
    public class func getFormTrackingAsCsvWithRequestBuilder(id id: String) -> RequestBuilder<Void> {
        var path = "/forms/{id}/tracking/export"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
