//
// ListsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class ListsAPI: APIBase {
    /**
     Clear Contacts from List
     
     - parameter listId: (path) The list to be cleared. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func clearList(listId listId: String, completion: ((error: ErrorType?) -> Void)) {
        clearListWithRequestBuilder(listId: listId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Clear Contacts from List
     - PUT /lists/{listId}/clear
     - Clears all contacts from a list.
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     
     - parameter listId: (path) The list to be cleared. 

     - returns: RequestBuilder<Void> 
     */
    public class func clearListWithRequestBuilder(listId listId: String) -> RequestBuilder<Void> {
        var path = "/lists/{listId}/clear"
        path = path.stringByReplacingOccurrencesOfString("{listId}", withString: "\(listId)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Copy All Contacts from a List
     
     - parameter fromListId: (form) The list to be cleared. 
     - parameter listId: (path) The list to be cleared. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func copyListContacts(fromListId fromListId: String, listId: String, completion: ((error: ErrorType?) -> Void)) {
        copyListContactsWithRequestBuilder(fromListId: fromListId, listId: listId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Copy All Contacts from a List
     - POST /lists/{listId}/copy
     - Copy all contacts from a list.
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     
     - parameter fromListId: (form) The list to be cleared. 
     - parameter listId: (path) The list to be cleared. 

     - returns: RequestBuilder<Void> 
     */
    public class func copyListContactsWithRequestBuilder(fromListId fromListId: String, listId: String) -> RequestBuilder<Void> {
        var path = "/lists/{listId}/copy"
        path = path.stringByReplacingOccurrencesOfString("{listId}", withString: "\(listId)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "fromListId": fromListId
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Suppress All Contacts from List
     
     - parameter listId: (path) The list to be cleared. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func suppressAllInList(listId listId: String, completion: ((error: ErrorType?) -> Void)) {
        suppressAllInListWithRequestBuilder(listId: listId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Suppress All Contacts from List
     - PUT /lists/{listId}/suppress
     - Suppresses all contacts in a list.
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     
     - parameter listId: (path) The list to be cleared. 

     - returns: RequestBuilder<Void> 
     */
    public class func suppressAllInListWithRequestBuilder(listId listId: String) -> RequestBuilder<Void> {
        var path = "/lists/{listId}/suppress"
        path = path.stringByReplacingOccurrencesOfString("{listId}", withString: "\(listId)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
