//
// TeamsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class TeamsAPI: APIBase {
    /**
     Add Member to Team
     
     - parameter teamId: (path) The team id 
     - parameter admin: (form) Set if the user is an admin of this team. (optional)
     - parameter subgroupIds: (form) Subgroup IDs to add user to (optional)
     - parameter userEmail: (form) The email of the member being added to the team. (optional)
     - parameter userId: (form) The user id of the member being added to the team. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func addTeamMember(teamId teamId: String, admin: Bool? = nil, subgroupIds: String? = nil, userEmail: String? = nil, userId: String? = nil, completion: ((data: String?, error: ErrorType?) -> Void)) {
        addTeamMemberWithRequestBuilder(teamId: teamId, admin: admin, subgroupIds: subgroupIds, userEmail: userEmail, userId: userId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Add Member to Team
     - POST /team/{teamId}/member
     - Adds a member to a team.
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     - examples: [{contentType=application/json, example=""}]
     
     - parameter teamId: (path) The team id 
     - parameter admin: (form) Set if the user is an admin of this team. (optional)
     - parameter subgroupIds: (form) Subgroup IDs to add user to (optional)
     - parameter userEmail: (form) The email of the member being added to the team. (optional)
     - parameter userId: (form) The user id of the member being added to the team. (optional)

     - returns: RequestBuilder<String> 
     */
    public class func addTeamMemberWithRequestBuilder(teamId teamId: String, admin: Bool? = nil, subgroupIds: String? = nil, userEmail: String? = nil, userId: String? = nil) -> RequestBuilder<String> {
        var path = "/team/{teamId}/member"
        path = path.stringByReplacingOccurrencesOfString("{teamId}", withString: "\(teamId)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "admin": admin,
            "subgroupIds": subgroupIds,
            "userEmail": userEmail,
            "userId": userId
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<String>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Add users to group.
     
     - parameter teamId: (path) The team id 
     - parameter userDetails: (form) Array of emails or objects containing details needed to create user 
     - parameter sendWelcomeEmail: (form) Whether to send welcome email to new users (optional)
     - parameter subgroupIds: (form) Subgroup IDs to add user to (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func addUsers(teamId teamId: String, userDetails: String, sendWelcomeEmail: String? = nil, subgroupIds: String? = nil, completion: ((error: ErrorType?) -> Void)) {
        addUsersWithRequestBuilder(teamId: teamId, userDetails: userDetails, sendWelcomeEmail: sendWelcomeEmail, subgroupIds: subgroupIds).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Add users to group.
     - POST /team/{teamId}/members
     - Add a new or existing user to group.
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     
     - parameter teamId: (path) The team id 
     - parameter userDetails: (form) Array of emails or objects containing details needed to create user 
     - parameter sendWelcomeEmail: (form) Whether to send welcome email to new users (optional)
     - parameter subgroupIds: (form) Subgroup IDs to add user to (optional)

     - returns: RequestBuilder<Void> 
     */
    public class func addUsersWithRequestBuilder(teamId teamId: String, userDetails: String, sendWelcomeEmail: String? = nil, subgroupIds: String? = nil) -> RequestBuilder<Void> {
        var path = "/team/{teamId}/members"
        path = path.stringByReplacingOccurrencesOfString("{teamId}", withString: "\(teamId)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "userDetails": userDetails,
            "sendWelcomeEmail": sendWelcomeEmail,
            "subgroupIds": subgroupIds
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Add members to group from CSV
     
     - parameter teamId: (path) The team id 
     - parameter csvImportId: (form) ID of the CSV to import 
     - parameter map: (form) Object to use when mapping import to AccountCreateDetails. Key is property name on details, value is CSV column number. 
     - parameter sendWelcomeEmail: (form) Whether to send welcome email to new users (optional)
     - parameter subgroupIds: (form) Subgroup IDs to add user to (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func addUsersFromCsv(teamId teamId: String, csvImportId: String, map: String, sendWelcomeEmail: String? = nil, subgroupIds: String? = nil, completion: ((error: ErrorType?) -> Void)) {
        addUsersFromCsvWithRequestBuilder(teamId: teamId, csvImportId: csvImportId, map: map, sendWelcomeEmail: sendWelcomeEmail, subgroupIds: subgroupIds).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Add members to group from CSV
     - POST /team/{teamId}/members/csv
     - Imports members to a group from a given CSV ID.
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     
     - parameter teamId: (path) The team id 
     - parameter csvImportId: (form) ID of the CSV to import 
     - parameter map: (form) Object to use when mapping import to AccountCreateDetails. Key is property name on details, value is CSV column number. 
     - parameter sendWelcomeEmail: (form) Whether to send welcome email to new users (optional)
     - parameter subgroupIds: (form) Subgroup IDs to add user to (optional)

     - returns: RequestBuilder<Void> 
     */
    public class func addUsersFromCsvWithRequestBuilder(teamId teamId: String, csvImportId: String, map: String, sendWelcomeEmail: String? = nil, subgroupIds: String? = nil) -> RequestBuilder<Void> {
        var path = "/team/{teamId}/members/csv"
        path = path.stringByReplacingOccurrencesOfString("{teamId}", withString: "\(teamId)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "csvImportId": csvImportId,
            "map": map,
            "sendWelcomeEmail": sendWelcomeEmail,
            "subgroupIds": subgroupIds
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Cancel a Jericho Send
     
     - parameter jerichoId: (path) ID of the Jericho Job to cancel 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func cancelJerichoSend(jerichoId jerichoId: String, completion: ((error: ErrorType?) -> Void)) {
        cancelJerichoSendWithRequestBuilder(jerichoId: jerichoId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Cancel a Jericho Send
     - DELETE /team/{teamId}/jericho/{jerichoId}
     - Cancels a scheduled Jericho send from being sent.
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     
     - parameter jerichoId: (path) ID of the Jericho Job to cancel 

     - returns: RequestBuilder<Void> 
     */
    public class func cancelJerichoSendWithRequestBuilder(jerichoId jerichoId: String) -> RequestBuilder<Void> {
        var path = "/team/{teamId}/jericho/{jerichoId}"
        path = path.stringByReplacingOccurrencesOfString("{jerichoId}", withString: "\(jerichoId)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Add a Subteam
     
     - parameter teamId: (path) The team id 
     - parameter name: (form) The subteam&#39;s name. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func createSubteam(teamId teamId: String, name: String, completion: ((data: TeamPublicRepresentation?, error: ErrorType?) -> Void)) {
        createSubteamWithRequestBuilder(teamId: teamId, name: name).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Add a Subteam
     - POST /team/{teamId}/subteam
     - Adds a subteam to a parent team
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     - examples: [{contentType=application/json, example={
  "createdDate" : "createdDate",
  "name" : "name",
  "id" : "id"
}}]
     
     - parameter teamId: (path) The team id 
     - parameter name: (form) The subteam&#39;s name. 

     - returns: RequestBuilder<TeamPublicRepresentation> 
     */
    public class func createSubteamWithRequestBuilder(teamId teamId: String, name: String) -> RequestBuilder<TeamPublicRepresentation> {
        var path = "/team/{teamId}/subteam"
        path = path.stringByReplacingOccurrencesOfString("{teamId}", withString: "\(teamId)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "name": name
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<TeamPublicRepresentation>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Delete Subteam
     
     - parameter teamId: (path) The team id 
     - parameter subteamId: (form) The subteam you wish to delete. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func deleteSubteam(teamId teamId: String, subteamId: String, completion: ((data: String?, error: ErrorType?) -> Void)) {
        deleteSubteamWithRequestBuilder(teamId: teamId, subteamId: subteamId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Delete Subteam
     - DELETE /team/{teamId}/subteam
     - Deletes a subteam
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     - examples: [{contentType=application/json, example=""}]
     
     - parameter teamId: (path) The team id 
     - parameter subteamId: (form) The subteam you wish to delete. 

     - returns: RequestBuilder<String> 
     */
    public class func deleteSubteamWithRequestBuilder(teamId teamId: String, subteamId: String) -> RequestBuilder<String> {
        var path = "/team/{teamId}/subteam"
        path = path.stringByReplacingOccurrencesOfString("{teamId}", withString: "\(teamId)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "subteamId": subteamId
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<String>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Lists team associations
     
     - parameter clientId: (query) The clientId requesting group associations. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getAllClientGroupAssociations(clientId clientId: String, completion: ((error: ErrorType?) -> Void)) {
        getAllClientGroupAssociationsWithRequestBuilder(clientId: clientId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Lists team associations
     - GET /team/associations/
     - Returns a collection of team associations for a given user
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     
     - parameter clientId: (query) The clientId requesting group associations. 

     - returns: RequestBuilder<Void> 
     */
    public class func getAllClientGroupAssociationsWithRequestBuilder(clientId clientId: String) -> RequestBuilder<Void> {
        let path = "/team/associations/"
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "clientId": clientId
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     * enum for parameter assetType
     */
    public enum AssetType_getClientGroupAssets: String { 
        case Email = "email"
        case Video = "video"
    }

    /**
     Lists team assets
     
     - parameter assetType: (query) The type of assets. 
     - parameter teamId: (query) The team containing the assets. (optional)
     - parameter autoTagName: (query) The auto tag name containing the assets. (optional)
     - parameter pageSize: (query) The number of items to retrieve in a single db query. (optional)
     - parameter page: (query) Zero-based index of the page of data to retrieve from the db. (optional)
     - parameter search: (query) Search words. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getClientGroupAssets(assetType assetType: AssetType_getClientGroupAssets, teamId: String? = nil, autoTagName: String? = nil, pageSize: String? = nil, page: String? = nil, search: String? = nil, completion: ((data: InlineResponse200?, error: ErrorType?) -> Void)) {
        getClientGroupAssetsWithRequestBuilder(assetType: assetType, teamId: teamId, autoTagName: autoTagName, pageSize: pageSize, page: page, search: search).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Lists team assets
     - GET /team/assets/
     - Returns a collection of assets
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     - examples: [{contentType=application/json, example={
  "totalPages" : 0,
  "items" : [ {
    "name" : "name",
    "id" : "id",
    "thumbUrl" : "thumbUrl",
    "userId" : "userId"
  }, {
    "name" : "name",
    "id" : "id",
    "thumbUrl" : "thumbUrl",
    "userId" : "userId"
  } ]
}}]
     
     - parameter assetType: (query) The type of assets. 
     - parameter teamId: (query) The team containing the assets. (optional)
     - parameter autoTagName: (query) The auto tag name containing the assets. (optional)
     - parameter pageSize: (query) The number of items to retrieve in a single db query. (optional)
     - parameter page: (query) Zero-based index of the page of data to retrieve from the db. (optional)
     - parameter search: (query) Search words. (optional)

     - returns: RequestBuilder<InlineResponse200> 
     */
    public class func getClientGroupAssetsWithRequestBuilder(assetType assetType: AssetType_getClientGroupAssets, teamId: String? = nil, autoTagName: String? = nil, pageSize: String? = nil, page: String? = nil, search: String? = nil) -> RequestBuilder<InlineResponse200> {
        let path = "/team/assets/"
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "assetType": assetType.rawValue,
            "teamId": teamId,
            "autoTagName": autoTagName,
            "pageSize": pageSize,
            "page": page,
            "search": search
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<InlineResponse200>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     * enum for parameter memberStatus
     */
    public enum MemberStatus_getClientGroupStatistics: String { 
        case All = "all"
        case Active = "active"
        case Inactive = "inactive"
        case SelfPaid = "self-paid"
    }

    /**
     Get Team statistics
     
     - parameter teamId: (path) The team id 
     - parameter memberStatus: (query) The status of members to query for (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getClientGroupStatistics(teamId teamId: String, memberStatus: MemberStatus_getClientGroupStatistics? = nil, completion: ((error: ErrorType?) -> Void)) {
        getClientGroupStatisticsWithRequestBuilder(teamId: teamId, memberStatus: memberStatus).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Get Team statistics
     - GET /team/{teamId}/stats
     - Get top level statistic data for a Team
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     
     - parameter teamId: (path) The team id 
     - parameter memberStatus: (query) The status of members to query for (optional)

     - returns: RequestBuilder<Void> 
     */
    public class func getClientGroupStatisticsWithRequestBuilder(teamId teamId: String, memberStatus: MemberStatus_getClientGroupStatistics? = nil) -> RequestBuilder<Void> {
        var path = "/team/{teamId}/stats"
        path = path.stringByReplacingOccurrencesOfString("{teamId}", withString: "\(teamId)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "memberStatus": memberStatus?.rawValue
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     List Jericho Sends
     
     - parameter teamId: (path) The team whose Jericho sends you wish to see. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getJerichoSends(teamId teamId: String, completion: ((data: [JerichoConfiguration]?, error: ErrorType?) -> Void)) {
        getJerichoSendsWithRequestBuilder(teamId: teamId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     List Jericho Sends
     - GET /team/{teamId}/jericho
     - Lists Jericho sends, both pending and sent.
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     - examples: [{contentType=application/json, example=[ {
  "promptBody" : "promptBody",
  "followUpVideoId" : "followUpVideoId",
  "emailBody" : "emailBody",
  "customInitialEmailSubjectLine" : "customInitialEmailSubjectLine",
  "clientGroupId" : "clientGroupId",
  "sendDate" : "2000-01-23T04:56:07.000+00:00",
  "isPrompt" : true,
  "emailId" : "emailId",
  "mediaType" : "mediaType",
  "exampleVideoId" : "exampleVideoId",
  "emailSubject" : "emailSubject",
  "promptSubject" : "promptSubject",
  "printToTemplate" : true,
  "sendWithoutVideo" : true,
  "id" : "id",
  "promptIntro" : "promptIntro",
  "status" : "status"
}, {
  "promptBody" : "promptBody",
  "followUpVideoId" : "followUpVideoId",
  "emailBody" : "emailBody",
  "customInitialEmailSubjectLine" : "customInitialEmailSubjectLine",
  "clientGroupId" : "clientGroupId",
  "sendDate" : "2000-01-23T04:56:07.000+00:00",
  "isPrompt" : true,
  "emailId" : "emailId",
  "mediaType" : "mediaType",
  "exampleVideoId" : "exampleVideoId",
  "emailSubject" : "emailSubject",
  "promptSubject" : "promptSubject",
  "printToTemplate" : true,
  "sendWithoutVideo" : true,
  "id" : "id",
  "promptIntro" : "promptIntro",
  "status" : "status"
} ]}]
     
     - parameter teamId: (path) The team whose Jericho sends you wish to see. 

     - returns: RequestBuilder<[JerichoConfiguration]> 
     */
    public class func getJerichoSendsWithRequestBuilder(teamId teamId: String) -> RequestBuilder<[JerichoConfiguration]> {
        var path = "/team/{teamId}/jericho"
        path = path.stringByReplacingOccurrencesOfString("{teamId}", withString: "\(teamId)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[JerichoConfiguration]>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Gets Jericho performance statistics
     
     - parameter jerichoId: (path) ID of the Jericho job 
     - parameter teamId: (path) ID of team through which Jericho was sent 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getJerichoStats(jerichoId jerichoId: String, teamId: String, completion: ((data: JerichoPerformance?, error: ErrorType?) -> Void)) {
        getJerichoStatsWithRequestBuilder(jerichoId: jerichoId, teamId: teamId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Gets Jericho performance statistics
     - GET /team/{teamId}/jericho/{jerichoId}/performance
     - Returns an aggregate view of the performance of a Jericho send
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     - examples: [{contentType=application/json, example={
  "promptsOptedOut" : 1,
  "bounce" : 7,
  "abuseComplaints" : 4,
  "delivered" : 2,
  "sent" : 6,
  "click" : 3,
  "uniqueLandingPageViews" : 5,
  "jerichoId" : 0,
  "promptsSent" : 1,
  "promptsWithRecordings" : 1,
  "uniqueViews" : 1,
  "landingPageViews" : 5,
  "open" : 9,
  "videoPlay" : 2,
  "contacts" : 7
}}]
     
     - parameter jerichoId: (path) ID of the Jericho job 
     - parameter teamId: (path) ID of team through which Jericho was sent 

     - returns: RequestBuilder<JerichoPerformance> 
     */
    public class func getJerichoStatsWithRequestBuilder(jerichoId jerichoId: String, teamId: String) -> RequestBuilder<JerichoPerformance> {
        var path = "/team/{teamId}/jericho/{jerichoId}/performance"
        path = path.stringByReplacingOccurrencesOfString("{jerichoId}", withString: "\(jerichoId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{teamId}", withString: "\(teamId)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<JerichoPerformance>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     * enum for parameter orderBy
     */
    public enum OrderBy_getPagedClientGroupMembers: String { 
        case Jobs = "jobs"
        case Logins = "logins"
        case Videos = "videos"
        case Contacts = "contacts"
        case Firstname = "firstName"
        case Lastname = "lastName"
        case Status = "status"
        case Isadmin = "isAdmin"
    }

    /**
     * enum for parameter orderDirection
     */
    public enum OrderDirection_getPagedClientGroupMembers: String { 
        case Asc = "ASC"
        case Desc = "DESC"
    }

    /**
     List Team Members
     
     - parameter teamId: (path) The team id 
     - parameter pageSize: (query) Amount of records to return in a page. 
     - parameter page: (query) The page to return. 
     - parameter status: (query) The status type to filter by. (optional)
     - parameter search: (query) Filter results with names that match the search term. (optional)
     - parameter orderBy: (query) Key to order results by (optional)
     - parameter orderDirection: (query) ASC or DESC (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getPagedClientGroupMembers(teamId teamId: String, pageSize: String, page: String, status: String? = nil, search: String? = nil, orderBy: OrderBy_getPagedClientGroupMembers? = nil, orderDirection: OrderDirection_getPagedClientGroupMembers? = nil, completion: ((error: ErrorType?) -> Void)) {
        getPagedClientGroupMembersWithRequestBuilder(teamId: teamId, pageSize: pageSize, page: page, status: status, search: search, orderBy: orderBy, orderDirection: orderDirection).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     List Team Members
     - GET /team/{teamId}/members
     - Get a paginated listing of Team members
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     
     - parameter teamId: (path) The team id 
     - parameter pageSize: (query) Amount of records to return in a page. 
     - parameter page: (query) The page to return. 
     - parameter status: (query) The status type to filter by. (optional)
     - parameter search: (query) Filter results with names that match the search term. (optional)
     - parameter orderBy: (query) Key to order results by (optional)
     - parameter orderDirection: (query) ASC or DESC (optional)

     - returns: RequestBuilder<Void> 
     */
    public class func getPagedClientGroupMembersWithRequestBuilder(teamId teamId: String, pageSize: String, page: String, status: String? = nil, search: String? = nil, orderBy: OrderBy_getPagedClientGroupMembers? = nil, orderDirection: OrderDirection_getPagedClientGroupMembers? = nil) -> RequestBuilder<Void> {
        var path = "/team/{teamId}/members"
        path = path.stringByReplacingOccurrencesOfString("{teamId}", withString: "\(teamId)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "pageSize": pageSize,
            "page": page,
            "status": status,
            "search": search,
            "orderBy": orderBy?.rawValue,
            "orderDirection": orderDirection?.rawValue
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Jericho Monthly Stats
     
     - parameter month: (path) The month whose Jericho sends you wish to see. 
     - parameter year: (path) The year whose Jericho sends you wish to see. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getPromptMonthlyStats(month month: String, year: String, completion: ((data: String?, error: ErrorType?) -> Void)) {
        getPromptMonthlyStatsWithRequestBuilder(month: month, year: year).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Jericho Monthly Stats
     - GET /team/{month}/{year}/monthStats
     - Jericho Monthly Stats
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     - examples: [{contentType=application/json, example=""}]
     
     - parameter month: (path) The month whose Jericho sends you wish to see. 
     - parameter year: (path) The year whose Jericho sends you wish to see. 

     - returns: RequestBuilder<String> 
     */
    public class func getPromptMonthlyStatsWithRequestBuilder(month month: String, year: String) -> RequestBuilder<String> {
        var path = "/team/{month}/{year}/monthStats"
        path = path.stringByReplacingOccurrencesOfString("{month}", withString: "\(month)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{year}", withString: "\(year)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<String>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Get Prompt Overview
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getPromptOverview(completion: ((data: String?, error: ErrorType?) -> Void)) {
        getPromptOverviewWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get Prompt Overview
     - GET /team/promptOverview
     - Get Prompt Overview
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     - examples: [{contentType=application/json, example=""}]

     - returns: RequestBuilder<String> 
     */
    public class func getPromptOverviewWithRequestBuilder() -> RequestBuilder<String> {
        let path = "/team/promptOverview"
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<String>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     List Subteams
     
     - parameter teamId: (path) The team id 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getSubteams(teamId teamId: String, completion: ((data: [TeamPublicRepresentation]?, error: ErrorType?) -> Void)) {
        getSubteamsWithRequestBuilder(teamId: teamId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     List Subteams
     - GET /team/{teamId}/subteam
     - Returns a collection of subteams for a parent team
     - examples: [{contentType=application/json, example=[ {
  "createdDate" : "createdDate",
  "name" : "name",
  "id" : "id"
}, {
  "createdDate" : "createdDate",
  "name" : "name",
  "id" : "id"
} ]}]
     
     - parameter teamId: (path) The team id 

     - returns: RequestBuilder<[TeamPublicRepresentation]> 
     */
    public class func getSubteamsWithRequestBuilder(teamId teamId: String) -> RequestBuilder<[TeamPublicRepresentation]> {
        var path = "/team/{teamId}/subteam"
        path = path.stringByReplacingOccurrencesOfString("{teamId}", withString: "\(teamId)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[TeamPublicRepresentation]>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Get aggregate stats for campaigns
     
     - parameter clientGroupId: (path) ID of the client group association 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getTeamPromptAggregateStats(clientGroupId clientGroupId: String, completion: ((error: ErrorType?) -> Void)) {
        getTeamPromptAggregateStatsWithRequestBuilder(clientGroupId: clientGroupId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Get aggregate stats for campaigns
     - GET /team/{clientGroupId}/campaign/stats
     - Get all the campaigns aggregate stats
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     
     - parameter clientGroupId: (path) ID of the client group association 

     - returns: RequestBuilder<Void> 
     */
    public class func getTeamPromptAggregateStatsWithRequestBuilder(clientGroupId clientGroupId: String) -> RequestBuilder<Void> {
        var path = "/team/{clientGroupId}/campaign/stats"
        path = path.stringByReplacingOccurrencesOfString("{clientGroupId}", withString: "\(clientGroupId)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Get campaigns for team
     
     - parameter clientGroupId: (path) ID of the client group association 
     - parameter searchTerm: (query) The value to search for in prompt subject (optional)
     - parameter currentPage: (query) The current page (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getTeamPromptCampaigns(clientGroupId clientGroupId: String, searchTerm: String? = nil, currentPage: String? = nil, completion: ((error: ErrorType?) -> Void)) {
        getTeamPromptCampaignsWithRequestBuilder(clientGroupId: clientGroupId, searchTerm: searchTerm, currentPage: currentPage).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Get campaigns for team
     - GET /team/{clientGroupId}/campaign
     - Get campaigns for the team and their stats
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     
     - parameter clientGroupId: (path) ID of the client group association 
     - parameter searchTerm: (query) The value to search for in prompt subject (optional)
     - parameter currentPage: (query) The current page (optional)

     - returns: RequestBuilder<Void> 
     */
    public class func getTeamPromptCampaignsWithRequestBuilder(clientGroupId clientGroupId: String, searchTerm: String? = nil, currentPage: String? = nil) -> RequestBuilder<Void> {
        var path = "/team/{clientGroupId}/campaign"
        path = path.stringByReplacingOccurrencesOfString("{clientGroupId}", withString: "\(clientGroupId)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "searchTerm": searchTerm,
            "currentPage": currentPage
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Invite a list to join the admin's social prompt team
     
     - parameter teamId: (form) The team id 
     - parameter listId: (form) List to invite to the social prompt team. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func inviteToSocialPromptTeam(teamId teamId: String, listId: String, completion: ((error: ErrorType?) -> Void)) {
        inviteToSocialPromptTeamWithRequestBuilder(teamId: teamId, listId: listId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Invite a list to join the admin's social prompt team
     - POST /teams/prompt/invite
     - Invite to Social Prompt Team
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     
     - parameter teamId: (form) The team id 
     - parameter listId: (form) List to invite to the social prompt team. 

     - returns: RequestBuilder<Void> 
     */
    public class func inviteToSocialPromptTeamWithRequestBuilder(teamId teamId: String, listId: String) -> RequestBuilder<Void> {
        let path = "/teams/prompt/invite"
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "teamId": teamId,
            "listId": listId
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Creates a Jericho send.
     
     - parameter config: (body) JSON representing a Jericho configuration 
     - parameter teamId: (path) The ID of the team. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func queueJerichoSend(config config: JerichoConfiguration, teamId: String, completion: ((data: JerichoConfiguration?, error: ErrorType?) -> Void)) {
        queueJerichoSendWithRequestBuilder(config: config, teamId: teamId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Creates a Jericho send.
     - POST /team/{teamId}/jericho
     - Sends email content on behalf of members of a client group. There are two forms this send can take:         Static Email, and Video Prompt. Static emails require only an emailId.         Video Prompts build emails dynamically and require most of the other fields.         You must be an administrator of a Team Account to use this method.
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     - examples: [{contentType=application/json, example={
  "promptBody" : "promptBody",
  "followUpVideoId" : "followUpVideoId",
  "emailBody" : "emailBody",
  "customInitialEmailSubjectLine" : "customInitialEmailSubjectLine",
  "clientGroupId" : "clientGroupId",
  "sendDate" : "2000-01-23T04:56:07.000+00:00",
  "isPrompt" : true,
  "emailId" : "emailId",
  "mediaType" : "mediaType",
  "exampleVideoId" : "exampleVideoId",
  "emailSubject" : "emailSubject",
  "promptSubject" : "promptSubject",
  "printToTemplate" : true,
  "sendWithoutVideo" : true,
  "id" : "id",
  "promptIntro" : "promptIntro",
  "status" : "status"
}}]
     
     - parameter config: (body) JSON representing a Jericho configuration 
     - parameter teamId: (path) The ID of the team. 

     - returns: RequestBuilder<JerichoConfiguration> 
     */
    public class func queueJerichoSendWithRequestBuilder(config config: JerichoConfiguration, teamId: String) -> RequestBuilder<JerichoConfiguration> {
        var path = "/team/{teamId}/jericho"
        path = path.stringByReplacingOccurrencesOfString("{teamId}", withString: "\(teamId)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path
        let parameters = config.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<JerichoConfiguration>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Remove Member from Team
     
     - parameter teamId: (path) The team id 
     - parameter userId: (path) The user id of the member being removed. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func removeMemberFromTeam(teamId teamId: String, userId: String, completion: ((data: String?, error: ErrorType?) -> Void)) {
        removeMemberFromTeamWithRequestBuilder(teamId: teamId, userId: userId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Remove Member from Team
     - DELETE /team/{teamId}/member/{userId}
     - Removes a member from a team.
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     - examples: [{contentType=application/json, example=""}]
     
     - parameter teamId: (path) The team id 
     - parameter userId: (path) The user id of the member being removed. 

     - returns: RequestBuilder<String> 
     */
    public class func removeMemberFromTeamWithRequestBuilder(teamId teamId: String, userId: String) -> RequestBuilder<String> {
        var path = "/team/{teamId}/member/{userId}"
        path = path.stringByReplacingOccurrencesOfString("{teamId}", withString: "\(teamId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{userId}", withString: "\(userId)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<String>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Resend invite
     
     - parameter teamId: (path) The team id 
     - parameter memberUserId: (path) The user id of the member being resent an invitation. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func resendTeamMemberInvitation(teamId teamId: String, memberUserId: String, completion: ((data: TeamPublicRepresentation?, error: ErrorType?) -> Void)) {
        resendTeamMemberInvitationWithRequestBuilder(teamId: teamId, memberUserId: memberUserId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Resend invite
     - POST /team/{teamId}/{memberUserId}/rewelcome
     - Resend invitation to a member of a team
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     - examples: [{contentType=application/json, example={
  "createdDate" : "createdDate",
  "name" : "name",
  "id" : "id"
}}]
     
     - parameter teamId: (path) The team id 
     - parameter memberUserId: (path) The user id of the member being resent an invitation. 

     - returns: RequestBuilder<TeamPublicRepresentation> 
     */
    public class func resendTeamMemberInvitationWithRequestBuilder(teamId teamId: String, memberUserId: String) -> RequestBuilder<TeamPublicRepresentation> {
        var path = "/team/{teamId}/{memberUserId}/rewelcome"
        path = path.stringByReplacingOccurrencesOfString("{teamId}", withString: "\(teamId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{memberUserId}", withString: "\(memberUserId)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<TeamPublicRepresentation>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Updates the Jericho Prompt Settings
     
     - parameter teamId: (path) The team id 
     - parameter jerichoId: (path) ID of the Jericho job 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func updateJerichoPromptSend(teamId teamId: String, jerichoId: String, completion: ((error: ErrorType?) -> Void)) {
        updateJerichoPromptSendWithRequestBuilder(teamId: teamId, jerichoId: jerichoId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Updates the Jericho Prompt Settings
     - PUT /team/{teamId}/jericho/{jerichoId}
     - Updates the prompt settings based on the original email id
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     
     - parameter teamId: (path) The team id 
     - parameter jerichoId: (path) ID of the Jericho job 

     - returns: RequestBuilder<Void> 
     */
    public class func updateJerichoPromptSendWithRequestBuilder(teamId teamId: String, jerichoId: String) -> RequestBuilder<Void> {
        var path = "/team/{teamId}/jericho/{jerichoId}"
        path = path.stringByReplacingOccurrencesOfString("{teamId}", withString: "\(teamId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{jerichoId}", withString: "\(jerichoId)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Update a team
     
     - parameter teamId: (path) The team id 
     - parameter name: (form) The name of the team (optional)
     - parameter state: (form) The status of the login permissions (optional)
     - parameter subteamsCanAddMembers: (form) Updates subteam member adding setting on group (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func updateTeam(teamId teamId: String, name: String? = nil, state: String? = nil, subteamsCanAddMembers: Bool? = nil, completion: ((data: TeamPublicRepresentation?, error: ErrorType?) -> Void)) {
        updateTeamWithRequestBuilder(teamId: teamId, name: name, state: state, subteamsCanAddMembers: subteamsCanAddMembers).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Update a team
     - POST /team/{teamId}
     - Update fields on a team
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     - examples: [{contentType=application/json, example={
  "createdDate" : "createdDate",
  "name" : "name",
  "id" : "id"
}}]
     
     - parameter teamId: (path) The team id 
     - parameter name: (form) The name of the team (optional)
     - parameter state: (form) The status of the login permissions (optional)
     - parameter subteamsCanAddMembers: (form) Updates subteam member adding setting on group (optional)

     - returns: RequestBuilder<TeamPublicRepresentation> 
     */
    public class func updateTeamWithRequestBuilder(teamId teamId: String, name: String? = nil, state: String? = nil, subteamsCanAddMembers: Bool? = nil) -> RequestBuilder<TeamPublicRepresentation> {
        var path = "/team/{teamId}"
        path = path.stringByReplacingOccurrencesOfString("{teamId}", withString: "\(teamId)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "name": name,
            "state": state,
            "subteamsCanAddMembers": subteamsCanAddMembers
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<TeamPublicRepresentation>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Update Member of Team
     
     - parameter teamId: (path) The team id 
     - parameter userId: (form) The user id of the member being added to the team. 
     - parameter admin: (form) Set if the user is an admin of this team. 
     - parameter permissionSuiteId: (form) Set if the user is an admin of this team. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func updateTeamMember(teamId teamId: String, userId: String, admin: Bool, permissionSuiteId: String? = nil, completion: ((error: ErrorType?) -> Void)) {
        updateTeamMemberWithRequestBuilder(teamId: teamId, userId: userId, admin: admin, permissionSuiteId: permissionSuiteId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Update Member of Team
     - PUT /team/{teamId}/member
     - Updates a member of a team
     - OAuth:
       - type: oauth2
       - name: BBOAuth2
     
     - parameter teamId: (path) The team id 
     - parameter userId: (form) The user id of the member being added to the team. 
     - parameter admin: (form) Set if the user is an admin of this team. 
     - parameter permissionSuiteId: (form) Set if the user is an admin of this team. (optional)

     - returns: RequestBuilder<Void> 
     */
    public class func updateTeamMemberWithRequestBuilder(teamId teamId: String, userId: String, admin: Bool, permissionSuiteId: String? = nil) -> RequestBuilder<Void> {
        var path = "/team/{teamId}/member"
        path = path.stringByReplacingOccurrencesOfString("{teamId}", withString: "\(teamId)", options: .LiteralSearch, range: nil)
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "userId": userId,
            "admin": admin,
            "permissionSuiteId": permissionSuiteId
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
