//
// UsersAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class UsersAPI: APIBase {
    /**
     Get client contact information.
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getClientContactInformation(completion: ((error: ErrorType?) -> Void)) {
        getClientContactInformationWithRequestBuilder().execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Get client contact information.
     - GET /clients/contact/information
     - Get the client contact information of the user's account.
     - OAuth:
       - type: oauth2
       - name: BBOAuth2

     - returns: RequestBuilder<Void> 
     */
    public class func getClientContactInformationWithRequestBuilder() -> RequestBuilder<Void> {
        let path = "/clients/contact/information"
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Get user profile information.
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getUserProfileInfo(completion: ((error: ErrorType?) -> Void)) {
        getUserProfileInfoWithRequestBuilder().execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Get user profile information.
     - GET /users/profile/information
     - Get the users profile information.
     - OAuth:
       - type: oauth2
       - name: BBOAuth2

     - returns: RequestBuilder<Void> 
     */
    public class func getUserProfileInfoWithRequestBuilder() -> RequestBuilder<Void> {
        let path = "/users/profile/information"
        let URLString = bombbomb-swift-openapiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = bombbomb-swift-openapiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
