//
// ClientGroupAssetMetaData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ClientGroupAssetMetaData: JSONEncodable {
    public var id: String?
    public var name: String?
    public var userId: String?
    public var thumbUrl: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["userId"] = self.userId
        nillableDictionary["thumbUrl"] = self.thumbUrl
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
