//
// CurriculumUserProgress.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The CurriculumUserProgress class */
public class CurriculumUserProgress: JSONEncodable {
    /** Id */
    public var id: String?
    /** User Id */
    public var userId: String?
    /** Curriculum Item Id */
    public var curriculumItemId: String?
    /** Curriculum Id */
    public var curriculumId: String?
    /** When the final email is scheduled to be sent */
    public var completedDate: NSDate?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["userId"] = self.userId
        nillableDictionary["curriculumItemId"] = self.curriculumItemId
        nillableDictionary["curriculumId"] = self.curriculumId
        nillableDictionary["completedDate"] = self.completedDate?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
