//
// Curriculum.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Curriculum class */
public class Curriculum: JSONEncodable {
    /** Id */
    public var id: String?
    /** Name */
    public var name: String?
    /** HTML formatted intro */
    public var htmlIntro: String?
    /** URI of header image */
    public var imgUrl: String?
    /** Number of curriculum items */
    public var itemCount: Int32?
    /** Render method for curriculum */
    public var renderAs: String?
    /** Globally visible */
    public var visibleToAllUsers: Bool?
    /** Collection of User Progress for Curriculum */
    public var progress: [CurriculumUserProgress]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["htmlIntro"] = self.htmlIntro
        nillableDictionary["imgUrl"] = self.imgUrl
        nillableDictionary["itemCount"] = self.itemCount?.encodeToJSON()
        nillableDictionary["renderAs"] = self.renderAs
        nillableDictionary["visibleToAllUsers"] = self.visibleToAllUsers
        nillableDictionary["progress"] = self.progress?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
