//
// HostedDoc.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The HostedDoc class */
public class HostedDoc: JSONEncodable {
    /** The doc&#39;s id. */
    public var id: String?
    /** The doc&#39;s owner. */
    public var userId: String?
    /** docs file name. */
    public var fileName: String?
    /** The doc&#39;s short url. */
    public var shortUrl: String?
    /** The doc&#39;s long url. */
    public var longUrl: String?
    /** The doc&#39;s upload date. */
    public var uploadDate: NSDate?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["userId"] = self.userId
        nillableDictionary["fileName"] = self.fileName
        nillableDictionary["shortUrl"] = self.shortUrl
        nillableDictionary["longUrl"] = self.longUrl
        nillableDictionary["uploadDate"] = self.uploadDate?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
