//
// OAuthClient.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class OAuthClient: JSONEncodable {
    /** The id of the OAuth Client */
    public var identifier: String?
    /** The user-facing name of the client. Eg. MyCrm */
    public var name: String?
    /** The secret supplied to the OAuth Application */
    public var clientSecret: String?
    /** The grants allowed */
    public var grantsAllowed: String?
    /** The user who controls the OAuth App */
    public var owningUserId: String?
    /** Where OAuth authorization sessions are returned to */
    public var redirectUri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["identifier"] = self.identifier
        nillableDictionary["name"] = self.name
        nillableDictionary["clientSecret"] = self.clientSecret
        nillableDictionary["grantsAllowed"] = self.grantsAllowed
        nillableDictionary["owningUserId"] = self.owningUserId
        nillableDictionary["redirectUri"] = self.redirectUri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
