//
// PromptBotBot.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The PromptBot\\Bot class */
public class PromptBotBot: JSONEncodable {
    /** The identifier of the prompt bot. Read Only. */
    public var id: String?
    /** The prompt bot&#39;s owner. Read Only. */
    public var userId: String?
    /** The default email being sent to contacts in the prompt bot list. */
    public var emailId: String?
    /** The list to attach the Prompt Bot to. */
    public var listId: String?
    /** The prompt subject. */
    public var promptSubject: String?
    /** The prompt body. */
    public var promptBody: String?
    /** The status of the prompt bot. Read Only. */
    public var status: String?
    /** when the bot started */
    public var startDate: NSDate?
    /** when the bot should finish */
    public var endDate: NSDate?
    /** The type of bot. */
    public var botTypeId: String?
    /** The template id used to generate the default email. */
    public var templateId: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["userId"] = self.userId
        nillableDictionary["emailId"] = self.emailId
        nillableDictionary["listId"] = self.listId
        nillableDictionary["promptSubject"] = self.promptSubject
        nillableDictionary["promptBody"] = self.promptBody
        nillableDictionary["status"] = self.status
        nillableDictionary["startDate"] = self.startDate?.encodeToJSON()
        nillableDictionary["endDate"] = self.endDate?.encodeToJSON()
        nillableDictionary["botTypeId"] = self.botTypeId
        nillableDictionary["templateId"] = self.templateId
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
