//
// PromptBot.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Prompt\\Bot class */
public class PromptBot: JSONEncodable {
    /** The identifier of the prompt bot. Read Only. */
    public var id: String?
    /** The prompt bot&#39;s owner. Read Only. */
    public var userId: String?
    /** The default email being sent to contacts in the prompt bot list. */
    public var emailId: String?
    /** The list to attach the Prompt Bot to. */
    public var listId: String?
    /** The name of the bot. */
    public var name: String?
    /** The custom contact field value column used for this bot. */
    public var contactFieldValueColumn: String?
    /** The status of the prompt bot. Read Only. */
    public var status: Int32?
    /** when the bot started */
    public var startDate: NSDate?
    /** when the bot should finish */
    public var endDate: NSDate?
    /** The type of bot. */
    public var botTypeId: String?
    /** The template id used to generate the default email. */
    public var templateId: String?
    /** The video that was added to the prompt. */
    public var videoId: String?
    /** The content to use in the email. */
    public var content: String?
    /** The subject of the default email. */
    public var subject: String?
    /** Set when generated as a default by a bot. */
    public var generatedBy: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["userId"] = self.userId
        nillableDictionary["emailId"] = self.emailId
        nillableDictionary["listId"] = self.listId
        nillableDictionary["name"] = self.name
        nillableDictionary["contactFieldValueColumn"] = self.contactFieldValueColumn
        nillableDictionary["status"] = self.status?.encodeToJSON()
        nillableDictionary["startDate"] = self.startDate?.encodeToJSON()
        nillableDictionary["endDate"] = self.endDate?.encodeToJSON()
        nillableDictionary["botTypeId"] = self.botTypeId
        nillableDictionary["templateId"] = self.templateId
        nillableDictionary["videoId"] = self.videoId
        nillableDictionary["content"] = self.content
        nillableDictionary["subject"] = self.subject
        nillableDictionary["generatedBy"] = self.generatedBy
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
