//
// SignUploadResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The SignUploadResponse class */
public class SignUploadResponse: JSONEncodable {
    /** Base64 encoded policy. */
    public var policy: String?
    /** Signature for policy. */
    public var signature: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["policy"] = self.policy
        nillableDictionary["signature"] = self.signature
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
