//
// SignUploadRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The SignUploadRequest class */
public class SignUploadRequest: JSONEncodable {
    /** when the upload will expire. */
    public var expiration: NSDate?
    /** Key/Value object of request conditions. */
    public var conditions: AnyObject?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["expiration"] = self.expiration?.encodeToJSON()
        nillableDictionary["conditions"] = self.conditions
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
