//
// TeamPublicRepresentation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The TeamPublicRepresentation class */
public class TeamPublicRepresentation: JSONEncodable {
    /** The id of the team */
    public var id: String?
    /** The name of the team */
    public var name: String?
    /** The date the team was created */
    public var createdDate: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["createdDate"] = self.createdDate
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
