//
// VideoPublicRepresentation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The VideoPublicRepresentation class */
public class VideoPublicRepresentation: JSONEncodable {
    /** The id of the video */
    public var id: String?
    /** The is of the owning user */
    public var userId: String?
    /** The status of the video */
    public var status: String?
    /** The name of the video */
    public var name: String?
    /** A description of the video */
    public var description: String?
    /** The url of the thumbnail for the video */
    public var thumbUrl: String?
    /** Urls to different formats of the video */
    public var videoUrls: [String]?
    /** The url to use to link to the video */
    public var shortUrl: String?
    /** The height of the video in pixels */
    public var height: Int32?
    /** The width of the video in pixels */
    public var width: Int32?
    /** The date the video was uploaded */
    public var uploadDate: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["userId"] = self.userId
        nillableDictionary["status"] = self.status
        nillableDictionary["name"] = self.name
        nillableDictionary["description"] = self.description
        nillableDictionary["thumbUrl"] = self.thumbUrl
        nillableDictionary["videoUrls"] = self.videoUrls?.encodeToJSON()
        nillableDictionary["shortUrl"] = self.shortUrl
        nillableDictionary["height"] = self.height?.encodeToJSON()
        nillableDictionary["width"] = self.width?.encodeToJSON()
        nillableDictionary["uploadDate"] = self.uploadDate
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
