//
// VideoEncodingStatusResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The VideoEncodingStatusResponse class */
public class VideoEncodingStatusResponse: JSONEncodable {
    /** Returns true if the video is done encoding and finalized. */
    public var isReady: Bool?
    /** Returns true if the video encoding process failed. */
    public var isFailed: Bool?
    /** 0-100 value indicating progress of video encoding process. */
    public var progress: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["isReady"] = self.isReady
        nillableDictionary["isFailed"] = self.isFailed
        nillableDictionary["progress"] = self.progress?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
