//
// VideoRecorderMethodResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The VideoRecorderMethodResponse class */
public class VideoRecorderMethodResponse: JSONEncodable {
    /** The id of the user for whom this video will be recorded */
    public var userId: String?
    /** The email address of the user for whom this video will be recorded */
    public var email: String?
    /** The client_id of the user for whom this video will be recorded */
    public var clientId: String?
    /** The id of the video that will be recorded */
    public var vidId: String?
    /** An HTML blob that displays a video recorder */
    public var content: String?
    /** The width of the video recorder */
    public var width: Int32?
    /** the Height of the video recorder */
    public var height: Int32?
    /** Whether communication from the recorder will be handled via HTTPS (always true) */
    public var https: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["user_id"] = self.userId
        nillableDictionary["email"] = self.email
        nillableDictionary["client_id"] = self.clientId
        nillableDictionary["vid_id"] = self.vidId
        nillableDictionary["content"] = self.content
        nillableDictionary["width"] = self.width?.encodeToJSON()
        nillableDictionary["height"] = self.height?.encodeToJSON()
        nillableDictionary["https"] = self.https
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
