//
// BBWebHook.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The BBWebHook class */
public class BBWebHook: JSONEncodable {
    /** The user to whom the webhook belongs */
    public var userId: String?
    /** The id of the hook */
    public var hookId: Int32?
    /** the url to send hook requests to */
    public var url: String?
    /** Whether the hook is displayed to the user */
    public var isHidden: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["userId"] = self.userId
        nillableDictionary["hookId"] = self.hookId?.encodeToJSON()
        nillableDictionary["url"] = self.url
        nillableDictionary["isHidden"] = self.isHidden
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
