//
// JerichoConfiguration.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class JerichoConfiguration: JSONEncodable {
    public var id: String?
    public var clientGroupId: String?
    /** When the email should be sent. */
    public var sendDate: NSDate?
    /** Determines whether this is a static or prompted send. */
    public var isPrompt: Bool?
    /** Static send: The Email to send on behalf of the group members. */
    public var emailId: String?
    /** Video Prompt: The subject line prompting the user to record a video. */
    public var promptSubject: String?
    /** Video Prompt: The HTML body of the email prompting the user to record a video. */
    public var promptBody: String?
    /** Video Prompt: The subject line of the final sent email */
    public var emailSubject: String?
    /** Video Prompt: The HTML body of the final sent email. */
    public var emailBody: String?
    /** Video Prompt: Whether to send the final email if no video was recorded. */
    public var sendWithoutVideo: Bool?
    /** The state of the send. */
    public var status: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["clientGroupId"] = self.clientGroupId
        nillableDictionary["sendDate"] = self.sendDate?.encodeToJSON()
        nillableDictionary["isPrompt"] = self.isPrompt
        nillableDictionary["emailId"] = self.emailId
        nillableDictionary["promptSubject"] = self.promptSubject
        nillableDictionary["promptBody"] = self.promptBody
        nillableDictionary["emailSubject"] = self.emailSubject
        nillableDictionary["emailBody"] = self.emailBody
        nillableDictionary["sendWithoutVideo"] = self.sendWithoutVideo
        nillableDictionary["status"] = self.status
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
